LabManagementWeb/Controllers/JobTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LabManagementWeb.DAL;
using LabManagementWeb.Models;

namespace LabManagementWeb.Controllers
{
    public class JobTypesController : Controller
    {
        private IJobTypesRepository jobTypesRepository;

        public JobTypesController()
        {
            this.jobTypesRepository = new JobTypesRepository(new ApplicationDbContext());
        }

        // GET: JobTypes
        [Authorize]
        public ActionResult Index()
        {
            var jobTypes = from j in jobTypesRepository.GetJobTypes()
                           select j;
            return View(jobTypes.ToList());
        }

        // GET: JobTypes/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobType jobType = jobTypesRepository.GetJobTypeByID(id);
            if (jobType == null)
            {
                return HttpNotFound();
            }
            return View(jobType);
        }

        // GET: JobTypes/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID,Description,Prefix,DateCreated,UserCreated,DateModified,UserModified")] JobType jobType)
        {
            if (ModelState.IsValid)
            {
                jobTypesRepository.InsertJobType(jobType);
                jobTypesRepository.Save();
                return RedirectToAction("Index");
            }

            return View(jobType);
        }

        // GET: JobTypes/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobType jobType = jobTypesRepository.GetJobTypeByID(id);
            if (jobType == null)
            {
                return HttpNotFound();
            }
            return View(jobType);
        }

        // POST: JobTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ID,Description,Prefix,DateCreated,UserCreated,DateModified,UserModified")] JobType jobType)
        {
            if (ModelState.IsValid)
            {
                jobTypesRepository.UpdateJobType(jobType);
                jobTypesRepository.Save();
                return RedirectToAction("Index");
            }
            return View(jobType);
        }

        // GET: JobTypes/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobType jobType = jobTypesRepository.GetJobTypeByID(id);
            if (jobType == null)
            {
                return HttpNotFound();
            }
            return View(jobType);
        }

        // POST: JobTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            JobType jobType = jobTypesRepository.GetJobTypeByID(id);
            jobTypesRepository.DeleteJobType(id);
            jobTypesRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                jobTypesRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LabManagementWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lab Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/Nav")

</head>
<body>
    @Html.Action("LeftNav", "Navigation")

    <div class="container body-content">
        <span style="font-size:30px;cursor:pointer;color:white" onclick="openNav()">&#9776;</span>
        <div class="container inner-body-content">
            @RenderBody()
        </div>
        <footer class="footer">
            <p>&copy; @DateTime.Now.Year - LabManagement</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LabManagementWeb/Views/Shared/_LoginPartialLeft.cshtml
@using Microsoft.AspNet.Identity
@using System.Web
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-left" }))
    {
    @Html.AntiForgeryToken()
    <input type="hidden" id="userName" name="userName" value="@User.Identity.GetUserName()" />
        @Html.ActionLink("Your Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
        @Html.ActionLink("Job Types", "Index", "JobTypes")
        @Html.ActionLink("Clients", "Index", "Clients")
        @Html.ActionLink("Jobs", "Index", "Jobs")
        <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
    }
}
else
{
        @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
        @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
}